### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by RoyTinker**

### CODE REVIEW

**Comment by mehdishojaei** [comment]
Thanks.

**Comment by RoyTinker** [comment]
Thanks for merging @mehdishojaei. Could you publish the latest version to npm?

**Comment by mahdi-shojaee** [comment]
@RoyTinker, I published that immediately after merging.

**Comment by RoyTinker** [comment]
Hm, I'm not seeing it: https://www.npmjs.com/package/grunt-amdcheck

It says the last version was published 4 years ago

**Comment by mahdi-shojaee** [comment]
Maybe your browser cached the page. Try a hard refresh.

**Comment by RoyTinker** [comment]
Tried in 3 different browsers. All say the same thing

image

**Comment by mahdi-shojaee** [comment]
Screen Shot 2019-12-17 at 12 56 28 AM

**Comment by RoyTinker** [comment]
Now I'm seeing the updated image. And it's loading correctly through NPM -- thanks. Sorry to bother you.

**Comment by mahdi-shojaee** [comment]
No problem. Thanks for your attention.

**Pull request merged**
