### PR TITLE
update grunt peerDep

### PR DESCRIPTION
**Pull request by vladikoff**
Ref https://github.com/gruntjs/grunt-docs/blob/master/Blog-2016-02-11-Grunt-1.0.0-rc1-released.md#peer-dependencies

### CODE REVIEW

**Comment by mehdishojaei** [comment]
Right, Thanks for your contribution.

**Comment by vladikoff** [comment]
@mehdishojaei Hey could you please publish a new version of this ? 

Thanks!

**Comment by mehdishojaei** [comment]
Thanks, Done.

**Comment by vladikoff** [comment]
Awesome :+1:

**Pull request merged**
